### ISSUE TITLE
Problem z Pluginem FunnyGuilds-Reloaded 1.8.x

### ISSUE THREAD

**Issue by Nolife8913** [Wruczek/FunnyGuilds-Reloaded#13]
Witajcie, pobrałem plugin FunnyGuilds i wgrałem go poprawnie, uruchomiłem serwer i w konsolce wyskoczyły mi errory mianowicie takie:
        at net.dzikoysk.panda.util.configuration.PandaConfiguration.<init>(PandaConfiguration.java:25)
        at net.dzikoysk.funnyguilds.data.Data.funnyguilds(Data.java:43)
       at net.dzikoysk.funnyguilds.data.Data.save(Data.java:36)
    at net.dzikoysk.funnyguilds.data.Manager.save(Manager.java:43)
        at net.dzikoysk.funnyguilds.util.thread.Action.execute(Action.java:49)
       at net.dzikoysk.funnyguilds.util.thread.IndependentThread.execute(IndependentThread.java:39)
        at net.dzikoysk.funnyguilds.util.thread.IndependentThread.run(IndependentThread.java:27)

Gdy wbijam na serwer i wpisuję /plugins niby plugin jest i do tego ma kolor zielony ale jak wpisuje /g lub /gildia to nic nie działa :( 
Proszę o pomoc 
**Posiadam silnik CraftBukit 1.8.x**

**Comment by Wruczek** [comment]
Projekt jest zawieszony.
Sprawdź wersję [TheMolkaPL](https://github.com/TheMolkaPL/FunnyGuilds), powinno działać na 1.8 (nie testowałem)

**Comment by Nolife8913** [comment]
Okey spróbuję , dzięki za odpowiedź

**Comment by Nolife8913** [comment]
Niestety nie działa znowu to samo :(

**Comment by TheMolkaPL** [comment]
Podaj log z włączenia serwera. Moja wersja, którą podał @Wruczek działa, aczkolwiek nie ma w niej tablisty.

**Comment by Wruczek** [comment]
Jeśli kliknąłeś w link "FunnyGuilds Releases" to pamiętaj, że odnosi się on do starego repozytorium Dzikoyska :P

Musisz sam skompilować ten plugin.

`git clone git://github.com/TheMolkaPL/FunnyGuilds`
`cd FunnyGuilds`
`mvn clean package`
(powinno zadziałać)

**Comment by Nolife8913** [comment]
``` java
[21:32:17 INFO]: Starting minecraft server version 1.8.8
[21:32:17 INFO]: Loading properties
[21:32:17 INFO]: Default game type: SURVIVAL
[21:32:17 INFO]: This server is running CraftBukkit version git-Spigot-fdc1440-53fac9f (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[21:32:17 INFO]: Debug logging is disabled
[21:32:17 INFO]: Server Ping Player Sample Count: 12
[21:32:17 INFO]: Using 4 threads for Netty based IO
[21:32:17 INFO]: Generating keypair
[21:32:17 INFO]: Starting Minecraft server on 25.77.160.145:25565
[21:32:17 INFO]: Using default channel type
[21:32:17 INFO]: Set PluginClassLoader as parallel capable
[21:32:17 INFO]: [FunnyGuilds] Loading FunnyGuilds v3.9.9.1 Cleaned
[21:32:18 ERROR]: net/minecraft/util/com/google/common/base/Charsets initializing FunnyGuilds v3.9.9.1 Cleaned (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/util/com/google/common/base/Charsets
        at net.dzikoysk.panda.util.configuration.util.ConfigurationUtils.getLines(ConfigurationUtils.java:38) ~[?:?]
        at net.dzikoysk.panda.util.configuration.PandaConfiguration.<init>(PandaConfiguration.java:25) ~[?:?]
        at net.dzikoysk.funnyguilds.data.Settings.update(Settings.java:183) ~[?:?]
        at net.dzikoysk.funnyguilds.data.Settings.<init>(Settings.java:178) ~[?:?]
        at net.dzikoysk.funnyguilds.data.Settings.getInstance(Settings.java:438) ~[?:?]
        at net.dzikoysk.funnyguilds.FunnyGuilds.onLoad(FunnyGuilds.java:61) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:297) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
        at java.lang.Thread.run(Unknown Source) [?:1.7.0_79]
Caused by: java.lang.ClassNotFoundException: net.minecraft.util.com.google.common.base.Charsets
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_79]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_79]
        ... 10 more
[21:32:18 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[21:32:18 WARN]: The server will make no attempt to authenticate usernames. Beware.
[21:32:18 WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[21:32:18 WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[21:32:18 INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[21:32:18 INFO]: Preparing level "world"
[21:32:18 INFO]: -------- World Settings For [world] --------
[21:32:18 INFO]: Item Despawn Rate: 6000
[21:32:18 INFO]: Arrow Despawn Rate: 1200
[21:32:18 INFO]: Item Merge Radius: 2.5
[21:32:18 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[21:32:18 INFO]: View Distance: 10
[21:32:18 INFO]: Zombie Aggressive Towards Villager: true
[21:32:18 INFO]: Cactus Growth Modifier: 100%
[21:32:18 INFO]: Cane Growth Modifier: 100%
[21:32:18 INFO]: Melon Growth Modifier: 100%
[21:32:18 INFO]: Mushroom Growth Modifier: 100%
[21:32:18 INFO]: Pumpkin Growth Modifier: 100%
[21:32:18 INFO]: Sapling Growth Modifier: 100%
[21:32:18 INFO]: Wheat Growth Modifier: 100%
[21:32:18 INFO]: NetherWart Growth Modifier: 100%
[21:32:18 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[21:32:18 INFO]: Nerfing mobs spawned from spawners: false
[21:32:18 INFO]: Sending up to 5 chunks per packet
[21:32:18 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[21:32:18 INFO]: Max Entity Collisions: 8
[21:32:18 INFO]: Experience Merge Radius: 3.0
[21:32:18 INFO]: Chunks to Grow per Tick: 650
[21:32:18 INFO]: Clear tick list: false
[21:32:18 INFO]: Anti X-Ray: true
[21:32:18 INFO]:        Engine Mode: 1
[21:32:18 INFO]:        Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[21:32:18 INFO]:        Replace Blocks: [1, 5]
[21:32:18 INFO]: Mob Spawn Range: 4
[21:32:18 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[21:32:18 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[21:32:18 INFO]: Random Lighting Updates: false
[21:32:18 INFO]: Structure Info Saving: true
[21:32:18 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[21:32:18 INFO]: Max TNT Explosions: 100
[21:32:18 INFO]: -------- World Settings For [world_nether] --------
[21:32:18 INFO]: Item Despawn Rate: 6000
[21:32:18 INFO]: Arrow Despawn Rate: 1200
[21:32:18 INFO]: Item Merge Radius: 2.5
[21:32:18 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[21:32:18 INFO]: View Distance: 10
[21:32:18 INFO]: Zombie Aggressive Towards Villager: true
[21:32:18 INFO]: Cactus Growth Modifier: 100%
[21:32:18 INFO]: Cane Growth Modifier: 100%
[21:32:18 INFO]: Melon Growth Modifier: 100%
[21:32:18 INFO]: Mushroom Growth Modifier: 100%
[21:32:18 INFO]: Pumpkin Growth Modifier: 100%
[21:32:18 INFO]: Sapling Growth Modifier: 100%
[21:32:18 INFO]: Wheat Growth Modifier: 100%
[21:32:18 INFO]: NetherWart Growth Modifier: 100%
[21:32:18 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[21:32:18 INFO]: Nerfing mobs spawned from spawners: false
[21:32:18 INFO]: Sending up to 5 chunks per packet
[21:32:18 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[21:32:18 INFO]: Max Entity Collisions: 8
[21:32:18 INFO]: Experience Merge Radius: 3.0
[21:32:18 INFO]: Chunks to Grow per Tick: 650
[21:32:18 INFO]: Clear tick list: false
[21:32:18 INFO]: Anti X-Ray: true
[21:32:18 INFO]:        Engine Mode: 1
[21:32:18 INFO]:        Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[21:32:18 INFO]:        Replace Blocks: [1, 5]
[21:32:18 INFO]: Mob Spawn Range: 4
[21:32:18 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[21:32:18 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[21:32:18 INFO]: Random Lighting Updates: false
[21:32:18 INFO]: Structure Info Saving: true
[21:32:18 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[21:32:18 INFO]: Max TNT Explosions: 100
[21:32:18 INFO]: -------- World Settings For [world_the_end] --------
[21:32:18 INFO]: Item Despawn Rate: 6000
[21:32:18 INFO]: Arrow Despawn Rate: 1200
[21:32:18 INFO]: Item Merge Radius: 2.5
[21:32:18 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[21:32:18 INFO]: View Distance: 10
[21:32:18 INFO]: Zombie Aggressive Towards Villager: true
[21:32:18 INFO]: Cactus Growth Modifier: 100%
[21:32:18 INFO]: Cane Growth Modifier: 100%
[21:32:18 INFO]: Melon Growth Modifier: 100%
[21:32:18 INFO]: Mushroom Growth Modifier: 100%
[21:32:18 INFO]: Pumpkin Growth Modifier: 100%
[21:32:18 INFO]: Sapling Growth Modifier: 100%
[21:32:18 INFO]: Wheat Growth Modifier: 100%
[21:32:18 INFO]: NetherWart Growth Modifier: 100%
[21:32:18 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[21:32:18 INFO]: Nerfing mobs spawned from spawners: false
[21:32:18 INFO]: Sending up to 5 chunks per packet
[21:32:18 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[21:32:18 INFO]: Max Entity Collisions: 8
[21:32:18 INFO]: Experience Merge Radius: 3.0
[21:32:18 INFO]: Chunks to Grow per Tick: 650
[21:32:18 INFO]: Clear tick list: false
[21:32:18 INFO]: Anti X-Ray: true
[21:32:18 INFO]:        Engine Mode: 1
[21:32:18 INFO]:        Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[21:32:18 INFO]:        Replace Blocks: [1, 5]
[21:32:18 INFO]: Mob Spawn Range: 4
[21:32:18 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[21:32:18 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[21:32:18 INFO]: Random Lighting Updates: false
[21:32:18 INFO]: Structure Info Saving: true
[21:32:18 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[21:32:18 INFO]: Max TNT Explosions: 100
[21:32:18 INFO]: Preparing start region for level 0 (Seed: -7492801512473941435)
[21:32:19 INFO]: Preparing spawn area: 53%
[21:32:20 INFO]: Preparing start region for level 1 (Seed: -1724595670470120702)
[21:32:20 INFO]: Preparing start region for level 2 (Seed: -1724595670470120702)
[21:32:20 INFO]: [FunnyGuilds] Enabling FunnyGuilds v3.9.9.1 Cleaned
[21:32:20 INFO]: [FunnyGuilds] Available Processors: 2
[21:32:20 INFO]: [FunnyGuilds] Active Threads: 10
[21:32:20 INFO]: [FunnyGuilds] Loaded users: 0
[21:32:20 INFO]: [FunnyGuilds] Loaded regions: 0
[21:32:20 INFO]: [FunnyGuilds] Loaded guilds: 0
[21:32:21 INFO]: [FunnyGuilds] ~ Created by & ę Dzikoysk ~
[21:32:21 INFO]: Server permissions file permissions.yml is empty, ignoring it
[21:32:21 INFO]: Done (2,906s)! For help, type "help" or "?"
[21:32:21 INFO]: Starting GS4 status listener
[21:32:21 INFO]: Query running on 25.77.160.145:25568
[21:32:21 INFO]: [FunnyGuilds][Updater] > You have a current version of FunnyGuilds.
[21:32:21 WARN]: Exception in thread "IndependentThread"
[21:32:21 WARN]: java.lang.NoClassDefFoundError: net/minecraft/util/com/google/common/base/Charsets
[21:32:21 WARN]:        at net.dzikoysk.panda.util.configuration.util.ConfigurationUtils.getLines(ConfigurationUtils.java:38)
[21:32:21 WARN]:        at net.dzikoysk.panda.util.configuration.PandaConfiguration.<init>(PandaConfiguration.java:25)
[21:32:21 WARN]:        at net.dzikoysk.funnyguilds.data.Data.funnyguilds(Data.java:43)
[21:32:21 WARN]:        at net.dzikoysk.funnyguilds.data.Data.save(Data.java:36)
[21:32:21 WARN]:        at net.dzikoysk.funnyguilds.data.Manager.save(Manager.java:43)
[21:32:21 WARN]:        at net.dzikoysk.funnyguilds.util.thread.Action.execute(Action.java:49)
[21:32:21 WARN]:        at net.dzikoysk.funnyguilds.util.thread.IndependentThread.execute(IndependentThread.java:39)
[21:32:21 WARN]:        at net.dzikoysk.funnyguilds.util.thread.IndependentThread.run(IndependentThread.java:27)
```

To są logi przy uruchamianiu serwa

**Comment by Wruczek** [comment]
To skompilowana wersja od @TheMolkaPL
Pobierz i powiedz czy działa.

[funnyguilds-1.8-3.9.9.1.jar.zip](https://github.com/Wruczek/FunnyGuilds-Reloaded/files/169906/funnyguilds-1.8-3.9.9.1.jar.zip)

U mnie śmiga.

**Comment by TheMolkaPL** [comment]
Przestarzała wersja pluginu. Nie posiadasz wersji pod 1.8, lecz pod starszy serwer. Musisz skompilować to samemu.

**Comment by Nolife8913** [comment]
Dobra, Dzięki wam za pomoc udało się wgrałem po prostu funnyguilds-1.8-3.9.9.1.jar.zip to i zadziałało 
Jeszcze raz dzięki Wam !!!!

**Comment by dekinght123** [comment]
ogólnie miałem też problem potem wgrałem prawie wszystko działa ale pod tabem ~~pisze mi~~ jest napisany tylko mój nick normalnie i nie ma ranku :/

**Comment by Wruczek** [comment]
Masz wersję zaktualizowaną do 1.8 z pominięciem taba. Został on wyłączony. Dlatego widzisz swój nick zamiast rankingu. W wersji na 1.7 wszystko powinno śmigać. A ranking powinien w pełni działać nawet na 1.8, sprawdź /ranking

**Comment by dekinght123** [comment]
/ranking działa ale pod tabem nie :/

**Comment by Wruczek** [comment]
Zobacz co napisałem wcześniej :)

**Comment by dekinght123** [comment]
znaczy tak mam 11,5 lat... xd a da się jakoś to ustawić?

**Comment by dekinght123** [comment]
więc mogę być tępy :3

**Comment by Wruczek** [comment]
###### ~~kill me~~

Obsługa tablisty została wyłączona w nieoficjalnej wersji pluginu na Minecraft 1.8
Jeżeli tak ci na tabie zależy, to zrób serwer na 1.7 wraz z pluginem na 1.7, będzie działać

**Comment by dekinght123** [comment]
ehh ok to jednak wole zostać bez taba bo nie chce mi się na 1.7 pluginów wgrywać i wszystkiego ustawiać :3
